### ISSUE TITLE
Loops load as a split of the first 2 Screens after On/Off (Sleep) Schedule ends

### ISSUE THREAD

**Issue by rsalsbery** [dakboard/Hardware-OPI-OS#10]
A user called to our attention that after rebooting from the On/Off (Sleep) Schedule that the Loop loads a split view of the first two screens of the loop and will not continue the loop. See Examples below:

![20230424_133440](https://user-images.githubusercontent.com/107418099/234075621-d7aa89fb-fb65-4270-9c01-c262f779e93a.jpg)

Testing shows a manual restart of the device corrects this without having to reassign the screen.

Current workarounds:

- Manually reboot the device after sleep ends
- Set the loop in a Schedule that starts a minute after the On/Off (Sleep) Schedule ends

**Comment by cocarrig** [comment]
A fix has been developed for the OPI-OS release, however an alternative redesign for the dakboard.com loops design has been confirmed as a solution as well.  As long as testing for the new loops design is successful no changes will be needed on the end device.  This case will be updated depending on the path taken.

**Comment by cocarrig** [comment]
A solution in dakboard.com has been identified to resolve this.  Development efforts completed on the OPI-OS will be closed and this case will be used to track release of the Cloud-platform fix developed.

**Comment by Dan-Peck** [comment]
Merged in @ d9994fd and added to the queue for upcoming release to the live site.
